### ISSUE TITLE
Permit2 error while passing calldata from Universal Router

### ISSUE THREAD

**Issue by clemsos** [Uniswap/smart-order-router#194]
- **I'm submitting a ...**
  [x] bug report

- **Summary**
Hello, 

I am running into a Permit2 issue (apparently) while trying to use the calldata returned by the Universal Router.

The process to get the route works correctly, but then the execution of the swap calldata reverts (without returning a reason). 

Running the tx in Tenderly, I get the following error:

```
Error Message: execution reverted
if (block.timestamp > allowed.expiration) revert AllowanceExpired(allowed.expiration);
at AllowanceTransfer.sol:79 in Permit2
```

I did approved both the Uniswap v3 router and also the Permit2 contract (as mentioned [here](https://docs.uniswap.org/contracts/permit2/overview#approving-permit2)) but the function still revert. Below is the hardhat script I sued (adapted from docs example) that can be run directly using a fork of mainnet.

Not sure what is happening here... any idea what I am doing wrong?

Many thanks !

```js
const { ethers, network } = require('hardhat')
const { AlphaRouter, SwapType } = require('@uniswap/smart-order-router')
const { Token, TradeType, CurrencyAmount, Percent } = require('@uniswap/sdk-core')
const { PERMIT2_ADDRESS } = require('@uniswap/universal-router-sdk')
const JSBI  = require('jsbi');

const V3_SWAP_ROUTER_ADDRESS = '0xEf1c6E67703c7BD7107eed8303Fbe6EC2554BF6B';
const MY_ADDRESS = '0x81a662065d5c83Fa9c5C12d0dc0104dF57f85A12'
const MAX_UINT = '115792089237316195423570985008687907853269984665640564039457584007913129639935'

// helpers
const impersonate = async (address) => {
  await network.provider.request({
    method: 'hardhat_impersonateAccount',
    params: [address],
  })
}

const addETH = async(address, amount = ethers.utils.parseEther('100')) => {
  const balance = ethers.utils.hexStripZeros(amount)
  await network.provider.send('hardhat_setBalance', [address, balance])
}

const addERC20 =  async function (tokenAddress, address, amount = 1000, decimals = 18 ) {
  // some whale that owns USDC
  const binance = '0xf977814e90da44bfa03b6295a0616a897441acec'
  const whale = await ethers.getSigner(binance)
  await impersonate(whale.address)

  const parsedAmount = amount = ethers.utils.parseUnits(amount, decimals)
  const erc20Contract = await ethers.getContractAt('@openzeppelin/contracts/token/ERC20/IERC20.sol:IERC20', tokenAddress)
  await erc20Contract.connect(whale).transfer(address, parsedAmount)
  console.log(`Transferred ${ethers.utils.formatUnits(await erc20Contract.balanceOf(address), decimals)}.`)
  return erc20Contract
}

const router = new AlphaRouter({ chainId: 1, provider: ethers.provider, });

const WETH = new Token(
  1,
  '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
  18,
  'WETH',
  'Wrapped Ether'
);

const USDC = new Token(
  1,
  '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
  6,
  'USDC',
  'USD//C'
);

// price is 100 USDC
const typedValueParsed = '100000000'
const usdcAmount = CurrencyAmount.fromRawAmount(USDC, JSBI.BigInt(typedValueParsed));

async function main () {
  const route = await router.route(
    usdcAmount,
    WETH,
    TradeType.EXACT_INPUT,
    {
      type: SwapType.UNIVERSAL_ROUTER,
      recipient: MY_ADDRESS,
      slippageTolerance: new Percent(5, 100),
      deadline: Math.floor(Date.now()/1000 +1800)
    }
  );

  console.log(`Quote Exact In: ${route.quote.toFixed(2)}`);
  console.log(`Gas Adjusted Quote In: ${route.quoteGasAdjusted.toFixed(2)}`);
  console.log(`Gas Used USD: ${route.estimatedGasUsedUSD.toFixed(6)}`);

  const transaction = {
    data: route.methodParameters.calldata,
    to: V3_SWAP_ROUTER_ADDRESS,
    value: 0,
    from: MY_ADDRESS,
    // gasPrice: BigNumber.from(route.gasPriceWei),
  };

  // fund the spender correctly
  const spender = await ethers.getSigner(MY_ADDRESS)
  await impersonate(spender.address)
  await addETH(spender.address)
  await addERC20(USDC.address, spender.address, '1000', '6') // 1000 USDC

  // permissions
  const token = await ethers.getContractAt('@openzeppelin/contracts/token/ERC20/IERC20.sol:IERC20', USDC.address)
  await token.connect(spender).approve(V3_SWAP_ROUTER_ADDRESS, MAX_UINT)
  await token.connect(spender).approve(PERMIT2_ADDRESS, MAX_UINT)

  console.log({
    spenderBalance: await token.balanceOf(spender.address),
    routerAllowance: await token.allowance(spender.address, V3_SWAP_ROUTER_ADDRESS),
    permit2Allowance: await token.allowance(spender.address, PERMIT2_ADDRESS)
  })

  const tx = await spender.sendTransaction(transaction)
  console.log(tx)
}


  
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })
```

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)

The ouptut log 
```
Running a mainnet fork...
Quote Exact In: 0.07
Gas Adjusted Quote In: 0.06
Gas Used USD: 7.997549
Transferred 1050.0.
{
  spenderBalance: BigNumber { value: "1050000000" },
  routerAllowance: BigNumber { value: "115792089237316195423570985008687907853269984665640564039457584007913129639935" },
  permit2Allowance: BigNumber { value: "115792089237316195423570985008687907853269984665640564039457584007913129639935" }
}
Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="Transaction reverted without a reason string", method="estimateGas", transaction={"from":"0x81a662065d5c83Fa9c5C12d0dc0104dF57f85A12","to":"0xEf1c6E67703c7BD7107eed8303Fbe6EC2554BF6B","data":"0x24856bc3000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000010000000000000000000000000081a662065d5c83fa9c5c12d0dc0104df57f85a120000000000000000000000000000000000000000000000000000000005f5e10000000000000000000000000000000000000000000000000000fcc0c29e81494400000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002ba0b86991c6218b36c1d19d4a2e9eb0ce3606eb480001f4c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000000000000000000000","accessList":null}, error={"stackTrace":[{"type":2,"address":{"type":"Buffer","data":[239,28,110,103,112,60,123,215,16,126,237,131,3,251,230,236,37,84,191,107]}},{"type":2,"address":{"type":"Buffer","data":[136,230,160,194,221,210,111,238,182,79,3,154,44,65,41,111,203,63,86,64]}},{"type":2,"address":{"type":"Buffer","data":[239,28,110,103,112,60,123,215,16,126,237,131,3,251,230,236,37,84,191,107]}},{"type":18,"address":{"type":"Buffer","data":[0,0,0,0,0,34,212,115,3,15,17,109,222,233,246,180,58,199,139,163]},"message":{"value":{"type":"Buffer","data":[216,27,47,46,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]},"_selector":"d81b2f2e"}}]}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (/Users/clement/Dev/unlock/unlock/node_modules/@ethersproject/logger/src.ts/index.ts:269:28)
    at Logger.throwError (/Users/clement/Dev/unlock/unlock/node_modules/@ethersproject/logger/src.ts/index.ts:281:20)
    at checkError (/Users/clement/Dev/unlock/unlock/node_modules/ethers/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:78:20)
    at EthersProviderWrapper.<anonymous> (/Users/clement/Dev/unlock/unlock/node_modules/ethers/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:642:20)
    at step (/Users/clement/Dev/unlock/unlock/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/Users/clement/Dev/unlock/unlock/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/Users/clement/Dev/unlock/unlock/node_modules/ethers/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'Transaction reverted without a reason string',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  method: 'estimateGas',
  transaction: {
    from: '0x81a662065d5c83Fa9c5C12d0dc0104dF57f85A12',
    to: '0xEf1c6E67703c7BD7107eed8303Fbe6EC2554BF6B',
    data: '0x24856bc3000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000010000000000000000000000000081a662065d5c83fa9c5c12d0dc0104df57f85a120000000000000000000000000000000000000000000000000000000005f5e10000000000000000000000000000000000000000000000000000fcc0c29e81494400000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000002ba0b86991c6218b36c1d19d4a2e9eb0ce3606eb480001f4c02aaa39b223fe8d0a0e5c4f27ead9083c756cc2000000000000000000000000000000000000000000',
    accessList: null
  },
  error: Error: Transaction reverted without a reason string
      at <UnrecognizedContract>.<unknown> (0x000000000022d473030f116ddee9f6b43ac78ba3)
      at <UnrecognizedContract>.<unknown> (0xef1c6e67703c7bd7107eed8303fbe6ec2554bf6b)
      at <UnrecognizedContract>.<unknown> (0x88e6a0c2ddd26feeb64f039a2c41296fcb3f5640)
      at <UnrecognizedContract>.<unknown> (0xef1c6e67703c7bd7107eed8303fbe6ec2554bf6b)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at EthModule._estimateGasAction (/Users/clement/Dev/unlock/unlock/node_modules/hardhat/src/internal/hardhat-network/provider/modules/eth.ts:425:7)
      at HardhatNetworkProvider.request (/Users/clement/Dev/unlock/unlock/node_modules/hardhat/src/internal/hardhat-network/provider/provider.ts:117:18)
      at EthersProviderWrapper.send (/Users/clement/Dev/unlock/unlock/packages/hardhat-plugin/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
}
```

**Comment by clemsos** [comment]
So after some more digging, I managed to answer my own question.

You need not only to approve Permit2 but also to pass set Permit2 permissions correctly. For that you have basically 2 ways: 1) parse the permit2 signature and pass it as the swapOptions `inputTokenPermit` params or 2) send a tx to permit2 directly to the contract with correct approval.

Below is the updated (and working) version of the script.

You can toggle the `usePermit2Sig` boolean to use either sig or tx to set perms in Permit2.

```js
const { ethers, network } = require('hardhat')
const { AlphaRouter, SwapType, MAX_UINT160 } = require('@uniswap/smart-order-router')
const { Token, TradeType, CurrencyAmount, Percent } = require('@uniswap/sdk-core')
const { PERMIT2_ADDRESS } = require('@uniswap/universal-router-sdk')
const { AllowanceTransfer } = require('@uniswap/permit2-sdk')
const JSBI  = require('jsbi');

const V3_SWAP_ROUTER_ADDRESS = '0xEf1c6E67703c7BD7107eed8303Fbe6EC2554BF6B';
const MAX_UINT = '115792089237316195423570985008687907853269984665640564039457584007913129639935'
const PERMIT2_APPROVE_ABI = [{
  "inputs": [
    {
      "internalType": "address",
      "name": "token",
      "type": "address"
    },
    {
      "internalType": "address",
      "name": "spender",
      "type": "address"
    },
    {
      "internalType": "uint160",
      "name": "amount",
      "type": "uint160"
    },
    {
      "internalType": "uint48",
      "name": "expiration",
      "type": "uint48"
    }
  ],
  "name": "approve",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function"
}]

// helpers
const impersonate = async (address) => {
  await network.provider.request({
    method: 'hardhat_impersonateAccount',
    params: [address],
  })
}

const addETH = async(address, amount = ethers.utils.parseEther('100')) => {
  const balance = ethers.utils.hexStripZeros(amount)
  await network.provider.send('hardhat_setBalance', [address, balance])
}

const getERC20Contract = async (tokenAddress) => 
   await ethers.getContractAt('@openzeppelin/contracts/token/ERC20/IERC20.sol:IERC20', tokenAddress)

const addERC20 =  async function (tokenAddress, address, amount = 1000, decimals = 18 ) {
  // some whale that owns USDC
  const binance = '0xf977814e90da44bfa03b6295a0616a897441acec'
  const whale = await ethers.getSigner(binance)
  await impersonate(whale.address)

  const parsedAmount = amount = ethers.utils.parseUnits(amount, decimals)
  const erc20Contract = await getERC20Contract(tokenAddress)
  await erc20Contract.connect(whale).transfer(address, parsedAmount)
  console.log(`Transferred ${ethers.utils.formatUnits(await erc20Contract.balanceOf(address), decimals)} to ${address}`)
  return erc20Contract
}

const makePermit = (
  tokenAddress,
  amount = ethers.constants.MaxUint256.toString(),
  nonce = '0'
) =>  {
  return {
    details: {
      token: tokenAddress,
      amount,
      expiration: Math.floor(new Date().getTime() / 1000 + 100000).toString(),
      nonce,
    },
    spender: V3_SWAP_ROUTER_ADDRESS,
    sigDeadline: Math.floor(new Date().getTime() / 1000 + 100000).toString(),
  }
}

async function generatePermitSignature(permit, signer, chainId) {
  const { domain, types, values } = AllowanceTransfer.getPermitData(permit, PERMIT2_ADDRESS, chainId)
  return await signer._signTypedData(domain, types, values)
}

const logBalance = async (token, signer) => {
  const usdc = await getERC20Contract(token.address)
  const balance = await usdc.balanceOf(signer.address)
  console.log(`${signer.address}: ${token.symbol} balance: `, balance.toString() )
}

const router = new AlphaRouter({ chainId: 1, provider: ethers.provider, });

const WETH = new Token(
  1,
  '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
  18,
  'WETH',
  'Wrapped Ether'
);

const USDC = new Token(
  1,
  '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
  6,
  'USDC',
  'USD//C'
);

const token0 = USDC
const token1 = WETH
const chainId = 1

// price is 1 WETH
const amount = '1'
const outAmountBN = ethers.utils.parseUnits(amount, token1.decimals)
const outAmount = CurrencyAmount.fromRawAmount(token1, JSBI.BigInt(outAmountBN));

// do we want to use signed message or send a tx?
const usePermit2Sig = false

async function main () {

  const [spender, recipient] = await ethers.getSigners()

  console.log(`spender: ${spender.address}`)
  console.log(`recipient: ${recipient.address}`)

  // max amount to permit for (5000 USDC)
  const permitAmount = ethers.utils.parseUnits('5000', 6)

  // fund the spender correctly
  await addETH(spender.address)
  await addERC20(token0.address, spender.address, '5000', 6)
  
  // check balances
  await logBalance(token0, spender)
  await logBalance(token1, recipient)
  
  // approve permit2 to manipulate token0 for us
  const token0_ERC20 = await getERC20Contract(token0.address)
  await token0_ERC20.connect(spender).approve(PERMIT2_ADDRESS, MAX_UINT)
  
  // permissions
  console.log(`Using Permit2 with ${usePermit2Sig ? 'signature' : 'litteral approval (tx)'}`)

  let permit, signature
  if (usePermit2Sig) {
    // create signed permit
    permit = makePermit(USDC.address, permitAmount.toString() )
    signature = await generatePermitSignature(permit, spender, chainId)
  } else {
    const permit2 = await ethers.getContractAt(PERMIT2_APPROVE_ABI, PERMIT2_ADDRESS)
    const txApproval = await permit2.approve(
      USDC.address,
      V3_SWAP_ROUTER_ADDRESS,
      MAX_UINT160,
      20_000_000_000_000 // expiration
    )
    const { transactionHash } = await txApproval.wait()
    console.log(`Approved premit2 to spend USDC at tx: ${transactionHash}`)
  }
  
  console.log(`Get quote for: ${token0.symbol} > ${outAmountBN.toString()} ${token1.symbol}`)
  const routeArgs = [
    outAmount,
    token0,
    TradeType.EXACT_OUTPUT,
    {
      type: SwapType.UNIVERSAL_ROUTER,
      recipient: recipient.address,
      slippageTolerance: new Percent(5, 100),
      deadline: Math.floor(Date.now()/1000 +1800)
    }
  ]

  // add Permit2 sig if needed
  if(usePermit2Sig) routeArgs.inputTokenPermit = {
    ...permit,
    signature,
  }
  
  const route = await router.route(...routeArgs)

  console.log(`Quote Exact In: ${route.quote.toFixed(2)}`);
  console.log(`Gas Adjusted Quote In: ${route.quoteGasAdjusted.toFixed(2)}`);
  console.log(`Gas Used USD: ${route.estimatedGasUsedUSD.toFixed(6)}`);

  console.log('Execture trade...')
  const transaction = {
    data: route.methodParameters.calldata,
    to: route.methodParameters.to,
    value: route.methodParameters.value,
    from: spender.address,
    // gasPrice: BigNumber.from(route.gasPriceWei),
  };

  const tx = await spender.sendTransaction(transaction)
  const { transactionHash: tradeHash } = await tx.wait()
  console.log(`Trade executed at ${tradeHash}.`)
  await logBalance(token0, spender)
  await logBalance(token1, recipient)
}


  
main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error)
    process.exit(1)
  })
```


which gives

```
Running a mainnet fork...
spender: 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
recipient: 0x70997970C51812dc3A010C7d01b50e0d17dc79C8
Transferred 5000.137975 to 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266
0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266: USDC balance:  5000137975
0x70997970C51812dc3A010C7d01b50e0d17dc79C8: WETH balance:  0
Using Permit2 with litteral approval (tx)
Approved premit2 to spend USDC at tx: 0xcaf8452d92e01ffcfd660b8b6183397456cf430421f586df90138e3f45b48b33
Get quote for: USDC > 1000000000000000000 WETH
Quote Exact In: 1332.65
Gas Adjusted Quote In: 1340.64
Gas Used USD: 7.990617
Execture trade...
Trade executed at 0x55cfbe4c1efb36a540e52e37f389909a86812fff62c2289acab41425584d9323.
0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266: USDC balance:  3667486708
0x70997970C51812dc3A010C7d01b50e0d17dc79C8: WETH balance:  1000000000000000000
```

The Uniswap docs to date is quite... sparse so hope that can help someone!

**Comment by s-pcode** [comment]
Hey @clemsos , you solution helped me a lot. I had few queries - 
1. Do we need to create the signed permit for every transaction ? Is this only required for erc20->erc20 ?
2. If a user signs the message but does not confirm the swap tx, and when he retries little later does he need to sign the permit again ?

**Comment by BranCat** [comment]
Perfectly solve the problem bothers me a long time. 
Thanks so much
