### ISSUE TITLE
Error: Unsupported swap type

### ISSUE THREAD

**Issue by roworld** [Uniswap/smart-order-router#239]
Hello!

My code is running in version 2.5.30 but chain id 56 is not supported in this version.
I updated the version to 3.11.4. Now I run my code and I get the error:
Error: Unsupported swap type [object Object]
    at buildSwapMethodParameters (/__testUniswap/node_modules/@uniswap/smart-order-router/build/main/util/methodParameters.js:105:11)
    at AlphaRouter.route (/__testUniswap/node_modules/@uniswap/smart-order-router/build/main/routers/alpha-router/alpha-router.js:461:81)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

My code in attached file

How i can fix it?

**Comment by roworld** [comment]
Fixed. In router.route call need to add in object SwapConfig type: SwapType.SWAP_ROUTER_02
<img width="551" alt="Снимок экрана 2023-05-30 в 13 10 20" src="https://github.com/Uniswap/smart-order-router/assets/134995591/37d45977-b395-4b9b-8f83-50ee10a5e707">

**Comment by jsy1218** [comment]
Glad you figured out. `SwapType.UNIVERSAL_ROUTER` would be preferred choice, since the web routes to universal router exclusively now.
