### ISSUE TITLE
Error: Invariant failed: CHAIN_ID on latest version (3.13.7)

### ISSUE THREAD

**Issue by tkeidar** [Uniswap/smart-order-router#287]
- **I'm submitting a ...**
  [X] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
After updating to latest version I get the following error on system startup, downgrade back to `3.13.5` solved it.

- **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. StackOverflow, personal fork, etc.)
```
/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14
    throw new Error(value);
          ^
Error: Invariant failed: CHAIN_ID
    at invariant (/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14:11)
    at Token.call (/node_modules/@uniswap/sdk-core/src/entities/baseCurrency.ts:43:5)
    at new Token (/node_modules/@uniswap/sdk-core/src/entities/token.ts:35:5)
    at Object.<anonymous> (/node_modules/@uniswap/smart-order-router/src/util/chains.ts:368:19)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Object.require.extensions.<computed> [as .js] (/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
```

**Comment by carlfairclough** [comment]
Same issue here. Downgrading resolved it..

**Comment by jsy1218** [comment]
Thanks for reporting the issue. We've added integration tests as part of our github workflow per pull request, so we expect to catch every compiling error in [smart-order-router](https://github.com/Uniswap/smart-order-router) repo.
