### ISSUE TITLE
call router.route(), get TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))

### ISSUE THREAD

**Issue by OneMore14** [Uniswap/smart-order-router#659]
- **I'm submitting a ...**
  [ ] bug report
  [ ] feature request
  [ ] question about the decisions made in the repository
  [ x ] question about how to use this project

- **Summary**
I'm trying to query USDT -> WETH routing on arbitrum one network, but always get this error
```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at _createForOfIteratorHelperLoose (/home/sunjian/Documents/owlto/dex-calldata-server/node_modules/@uniswap/router-sdk/dist/router-sdk.cjs.development.js:607:46)
    at new Trade (/home/sunjian/Documents/owlto/dex-calldata-server/node_modules/@uniswap/router-sdk/src/entities/trade.ts:80:5)
    at buildTrade (/home/sunjian/Documents/owlto/dex-calldata-server/node_modules/@uniswap/smart-order-router/src/util/methodParameters.ts:226:17)
    at calculateArbitrumToL1SecurityFee (/home/sunjian/Documents/owlto/dex-calldata-server/node_modules/@uniswap/smart-order-router/src/util/gas-factory-helpers.ts:659:29)
    at calculateL1GasFeesHelper (/home/sunjian/Documents/owlto/dex-calldata-server/node_modules/@uniswap/smart-order-router/src/util/gas-factory-helpers.ts:558:7)
    at Object.calculateL1GasFees (/home/sunjian/Documents/owlto/dex-calldata-server/node_modules/@uniswap/smart-order-router/src/routers/alpha-router/gas-models/v3/v3-heuristic-gas-model.ts:80:44)
    at getBestSwapRouteBy (/home/sunjian/Documents/owlto/dex-calldata-server/node_modules/@uniswap/smart-order-router/src/routers/alpha-router/functions/best-swap-route.ts:386:56)
    at getBestSwapRoute (/home/sunjian/Documents/owlto/dex-calldata-server/node_modules/@uniswap/smart-order-router/src/routers/alpha-router/functions/best-swap-route.ts:86:27)
    at AlphaRouter.getSwapRouteFromChain (/home/sunjian/Documents/owlto/dex-calldata-server/node_modules/@uniswap/smart-order-router/src/routers/alpha-router/alpha-router.ts:2061:49)
```

and here is my codes

```TypeScript
const USDT_TOKEN = new Token(
    42161,
    '0xfd086bc7cd5c481dcc9c85ebe478a1c0b69fcbb9', // https://arbiscan.io/address/0xaf88d065e77c8cc2239327c5edb3a432268e5831
    6,
    'USDT',
    'Tether USD'
)

const WETH_TOKEN = new Token(
    42161,  // a1 chain ID
    '0x82aF49447D8a07e3bd95BD0d56f35241523fBab1', // https://arbiscan.io/address/0x82af49447d8a07e3bd95bd0d56f35241523fbab1
    18,
    'WETH',
    'Wrapped Ether'
)

const rpcUrl = "https://arbitrum-mainnet.infura.io/v3/MY-TOKEN";

export async function v3() {
    const provider = new ethers.providers.JsonRpcProvider(rpcUrl);
    const tokenA = USDT_TOKEN;
    const tokenB = WETH_TOKEN;

    const chainId = 42161;
    const router = new AlphaRouter({
        chainId: chainId,
        provider: provider,
    });
    const options: SwapOptionsUniversalRouter = {
        recipient: walletAddress,
        slippageTolerance: new Percent(50, 10_000),
        deadlineOrPreviousBlockhash: Math.floor(Date.now() / 1000 + 1800),
        type: SwapType.UNIVERSAL_ROUTER,
    }
    const route = await router.route(
        CurrencyAmount.fromRawAmount(tokenA, 10000000),
        tokenB,
        TradeType.EXACT_INPUT,
        options
    );
    console.log(route);
}
```

hope to get some hints about why it does not work, thanks

**Comment by jfbloom22** [comment]
running into a similar error when trying to use this with Base Chain.

**Comment by yusufseyrek** [comment]
Same here

**Comment by OneMore14** [comment]
> Same here.
> 
> I updated the package to v3.40.0 and it fixed the issue for me.

It really helps! thank you

**Comment by OneMore14** [comment]
> Same here.
> 
> I updated the package to v3.40.0 and it fixed the issue for me.

It really helps! thank you !
