### ISSUE TITLE
Anyone can run demo in 'Integrating the Auto Router' from official doc?

### ISSUE THREAD

**Issue by 09ae9c** [Uniswap/smart-order-router#75]
- **I'm submitting a ...**
  [x] bug report

I follow the official doc in [Integrating the Auto Router'](https://docs.uniswap.org/sdk/guides/auto-router), and copy [The Full Example](https://docs.uniswap.org/sdk/guides/auto-router#the-full-example) to my local Environment, But it cannot run! all previous examples are run as expected except this one, so bad...

firstly, I install all dependencies like `ethers`, `@uniswap/smart-order-router`, `@uniswap/sdk-core`

and then I copy [The Full Example](https://docs.uniswap.org/sdk/guides/auto-router#the-full-example) to local, it shows some import errors, I import dependencies manually and replace `web3Provider` and `MY_ADDRESS` after that, all code is below:
```
import { BigNumber, ethers } from "ethers";
import { AlphaRouter, ChainId } from '@uniswap/smart-order-router'
import { Token, CurrencyAmount, Percent, TradeType } from '@uniswap/sdk-core'
import JSBI from "jsbi";

const V3_SWAP_ROUTER_ADDRESS = '0x68b3465833fb72A70ecDF485E0e4C7bD8665Fc45';
const MY_ADDRESS = "{MY_ADDRESS}";
const web3Provider = new ethers.providers.JsonRpcProvider("https://mainnet.infura.io/v3/{token}");
 

const router = new AlphaRouter({ chainId: 1, provider: web3Provider });

const WETH = new Token(
  1,
  '0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2',
  18,
  'WETH',
  'Wrapped Ether'
);

const USDC = new Token(
  ChainId.MAINNET,
  '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48',
  6,
  'USDC',
  'USD//C'
);

const typedValueParsed = '100000000000000000000'
const wethAmount = CurrencyAmount.fromRawAmount(USDC, JSBI.BigInt(typedValueParsed));

async function main() {

    const route = await router.route(
        wethAmount,
        USDC,
        TradeType.EXACT_INPUT,
        {
          recipient: MY_ADDRESS,
          slippageTolerance: new Percent(5, 100),
          deadline: Date.now() + 1800
        }
      );
      console.log(route)
    //   console.log(`Quote Exact In: ${route.quote.toFixed(2)}`);
    //   console.log(`Gas Adjusted Quote In: ${route.quoteGasAdjusted.toFixed(2)}`);
    //   console.log(`Gas Used USD: ${route.estimatedGasUsedUSD.toFixed(6)}`);
      
    //   const transaction = {
    //     data: route.methodParameters.calldata,
    //     to: V3_SWAP_ROUTER_ADDRESS,
    //     value: BigNumber.from(route.methodParameters.value),
    //     from: MY_ADDRESS,
    //     gasPrice: BigNumber.from(route.gasPriceWei),
    //   };
      
    //   await web3Provider.sendTransaction(transaction);    
}

main()
```

But when I run it with command `npx ts-node main.ts`, it will show error like this:

```
/Users/UniRouteTest/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14
    throw new Error(value);
          ^
Error: Invariant failed: ADDRESSES
    at invariant (/Users/UniRouteTest/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:14:11)
    at Token.sortsBefore (/Users/UniRouteTest/node_modules/@uniswap/sdk-core/src/entities/token.ts:39:5)
    at V3PoolProvider.getPoolAddress (/Users/UniRouteTest/node_modules/@uniswap/smart-order-router/src/providers/v3/pool-provider.ts:215:37)
    at CachingV3PoolProvider.getPoolAddress (/Users/UniRouteTest/node_modules/@uniswap/smart-order-router/src/providers/v3/caching-pool-provider.ts:107:30)
    at /Users/UniRouteTest/node_modules/@uniswap/smart-order-router/src/routers/alpha-router/functions/get-candidate-pools.ts:283:62
    at arrayMap (/Users/UniRouteTest/node_modules/lodash/lodash.js:653:23)
    at Function.map (/Users/UniRouteTest/node_modules/lodash/lodash.js:9622:14)
    at Object.getV3CandidatePools (/Users/UniRouteTest/node_modules/@uniswap/smart-order-router/src/routers/alpha-router/functions/get-candidate-pools.ts:280:28)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async AlphaRouter.getV3Quotes (/Users/UniRouteTest/node_modules/@uniswap/smart-order-router/src/routers/alpha-router/alpha-router.ts:1034:46)
```

I have Google these error output but nothing helped, any help?

**Comment by freeser** [comment]
How do you run the official demo successfully?
